from riva.prompts import (
    JOB_DESCRIPTION_PARSING_PROMPT,
    MATCHING_ANALYSIS_PROMPT,
    RESUME_PARSING_PROMPT,
)

RESUME_PARSING_ACCEPTED_PROMPT_VERSIONS = frozenset(
    {"1", "2", "3", RESUME_PARSING_PROMPT.version}
)
JOB_DESCRIPTION_PARSING_ACCEPTED_PROMPT_VERSIONS = frozenset(
    {"2", JOB_DESCRIPTION_PARSING_PROMPT.version}
)
MATCHING_ANALYSIS_ACCEPTED_PROMPT_VERSIONS = frozenset(
    {"1", MATCHING_ANALYSIS_PROMPT.version}
)
