from riva.schemas.auth import AuthCredentials, UserResponse
from riva.schemas.health import HealthResponse
from riva.schemas.health import DependencyHealthStatus, ServiceHealthStatus
from riva.schemas.job_description_parsing import (
    JobDescriptionParsingInput,
    JobDescriptionParsingOutput,
    JobDescriptionParsingRunPayload,
    QualificationRequirements,
    RequiredSkillGroups,
)
from riva.schemas.profile import (
    CareerProfileGetResponse,
    CareerProfilePutRequest,
    CareerProfilePutResponse,
    CareerProfileResponse,
)
from riva.schemas.matching_analysis import (
    MatchingAnalysisInput,
    MatchingAnalysisOutput,
    MatchingAnalysisRunPayload,
    MatchingCareerProfile,
    MatchingJobContext,
    MatchingProfileEducation,
    MatchingProfileProjectExperience,
    MatchingProfileWorkExperience,
)
from riva.schemas.roles import (
    ActiveTargetRolePreparationStatus,
    ArchiveTargetRoleRequest,
    CreateTargetRoleRequest,
    DeleteTargetRoleVersion,
    ExistingProfileContext,
    JobDescriptionResponse,
    MissingJobDescriptionResponse,
    MissingProfileContext,
    ProfileContext,
    RolesPageResponse,
    SaveJobDescriptionRequest,
    SavedJobDescriptionResponse,
    SetCurrentTargetRoleRequest,
    TargetRoleExperienceRange,
    TargetRolePreparationStatus,
    TargetRoleRecruitmentType,
    TargetRoleResponse,
    TargetRoleVersion,
    UpdatePreparationStatusRequest,
    UpdateTargetRoleRequest,
)
from riva.schemas.users import UserAccountResponse, UserAccountUpdate

__all__ = [
    "AuthCredentials",
    "DependencyHealthStatus",
    "HealthResponse",
    "CareerProfileGetResponse",
    "CareerProfilePutRequest",
    "CareerProfilePutResponse",
    "CareerProfileResponse",
    "JobDescriptionParsingInput",
    "JobDescriptionParsingOutput",
    "JobDescriptionParsingRunPayload",
    "QualificationRequirements",
    "RequiredSkillGroups",
    "MatchingAnalysisInput",
    "MatchingAnalysisOutput",
    "MatchingAnalysisRunPayload",
    "MatchingCareerProfile",
    "MatchingJobContext",
    "MatchingProfileEducation",
    "MatchingProfileProjectExperience",
    "MatchingProfileWorkExperience",
    "ActiveTargetRolePreparationStatus",
    "ArchiveTargetRoleRequest",
    "CreateTargetRoleRequest",
    "DeleteTargetRoleVersion",
    "ExistingProfileContext",
    "JobDescriptionResponse",
    "MissingJobDescriptionResponse",
    "MissingProfileContext",
    "ProfileContext",
    "RolesPageResponse",
    "SaveJobDescriptionRequest",
    "SavedJobDescriptionResponse",
    "ServiceHealthStatus",
    "SetCurrentTargetRoleRequest",
    "TargetRoleExperienceRange",
    "TargetRolePreparationStatus",
    "TargetRoleRecruitmentType",
    "TargetRoleResponse",
    "TargetRoleVersion",
    "UpdatePreparationStatusRequest",
    "UpdateTargetRoleRequest",
    "UserAccountResponse",
    "UserAccountUpdate",
    "UserResponse",
]
