"""Create the baseline schema for the current SQLAlchemy models."""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "202608160001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("normalized_username", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("avatar_url", sa.String(length=2083), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_normalized_username"),
        "users",
        ["normalized_username"],
        unique=True,
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("output_schema_id", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                name="agent_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'queued' AND attempt_count < max_attempts AND lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL AND finished_at IS NULL AND result IS NULL AND provider IS NULL AND input_tokens IS NULL AND output_tokens IS NULL) OR (status = 'running' AND attempt_count >= 1 AND lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL AND finished_at IS NULL AND result IS NULL AND provider IS NULL AND input_tokens IS NULL AND output_tokens IS NULL) OR (status = 'succeeded' AND attempt_count >= 1 AND lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL AND finished_at IS NOT NULL AND result IS NOT NULL AND provider IS NOT NULL AND input_tokens IS NOT NULL AND output_tokens IS NOT NULL AND error_code IS NULL) OR (status = 'failed' AND attempt_count >= 1 AND lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL AND finished_at IS NOT NULL AND result IS NULL AND provider IS NULL AND input_tokens IS NULL AND output_tokens IS NULL AND error_code IS NOT NULL)",
            name="ck_agent_runs_status_fields",
        ),
        sa.CheckConstraint(
            "(attempt_count = 0 AND started_at IS NULL) OR (attempt_count > 0 AND started_at IS NOT NULL)",
            name="ck_agent_runs_started_at",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1 AND attempt_count <= max_attempts",
            name="ck_agent_runs_attempts",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "agent_id",
            "prompt_id",
            "prompt_version",
            "idempotency_key",
            name="uq_agent_runs_idempotency",
        ),
    )
    op.create_index(
        "ix_agent_runs_expired_running",
        "agent_runs",
        ["lease_expires_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "ix_agent_runs_queued_available",
        "agent_runs",
        ["status", "available_at", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_agent_runs_user_created",
        "agent_runs",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"),
        "auth_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_token_digest"),
        "auth_sessions",
        ["token_digest"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "career_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "id", name="uq_career_profiles_user_id_id"),
    )
    op.create_index(
        op.f("ix_career_profiles_user_id"), "career_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "career_profile_educations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("career_profile_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("school", sa.String(length=255), nullable=False),
        sa.Column("degree", sa.String(length=255), nullable=True),
        sa.Column("major", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=7), nullable=False),
        sa.Column("end_date", sa.String(length=7), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0"),
        sa.ForeignKeyConstraint(
            ["career_profile_id"], ["career_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "career_profile_id", "position", deferrable=True, initially="DEFERRED"
        ),
    )
    op.create_index(
        op.f("ix_career_profile_educations_career_profile_id"),
        "career_profile_educations",
        ["career_profile_id"],
        unique=False,
    )
    op.create_table(
        "career_profile_project_experiences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("career_profile_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=7), nullable=False),
        sa.Column("end_date", sa.String(length=7), nullable=True),
        sa.Column("responsibilities", sa.JSON(), nullable=False),
        sa.Column("achievements", sa.JSON(), nullable=False),
        sa.Column("project_url", sa.String(length=2083), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0"),
        sa.ForeignKeyConstraint(
            ["career_profile_id"], ["career_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "career_profile_id", "position", deferrable=True, initially="DEFERRED"
        ),
    )
    op.create_index(
        op.f("ix_career_profile_project_experiences_career_profile_id"),
        "career_profile_project_experiences",
        ["career_profile_id"],
        unique=False,
    )
    op.create_table(
        "career_profile_skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("career_profile_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0"),
        sa.ForeignKeyConstraint(
            ["career_profile_id"], ["career_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "career_profile_id",
            "normalized_name",
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.UniqueConstraint(
            "career_profile_id", "position", deferrable=True, initially="DEFERRED"
        ),
    )
    op.create_index(
        op.f("ix_career_profile_skills_career_profile_id"),
        "career_profile_skills",
        ["career_profile_id"],
        unique=False,
    )
    op.create_table(
        "career_profile_work_experiences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("career_profile_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("employment_type", sa.String(length=32), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=7), nullable=False),
        sa.Column("end_date", sa.String(length=7), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("responsibilities", sa.JSON(), nullable=False),
        sa.Column("achievements", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0"),
        sa.ForeignKeyConstraint(
            ["career_profile_id"], ["career_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "career_profile_id", "position", deferrable=True, initially="DEFERRED"
        ),
    )
    op.create_index(
        op.f("ix_career_profile_work_experiences_career_profile_id"),
        "career_profile_work_experiences",
        ["career_profile_id"],
        unique=False,
    )
    op.create_table(
        "resume_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("extraction_status", sa.String(length=32), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("extraction_failure_code", sa.String(length=64), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parsing_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(extraction_status = 'pending' AND extracted_text IS NULL AND extraction_failure_code IS NULL AND extracted_at IS NULL) OR (extraction_status = 'succeeded' AND extracted_text IS NOT NULL AND length(trim(extracted_text)) > 0 AND extraction_failure_code IS NULL AND extracted_at IS NOT NULL) OR (extraction_status = 'failed' AND extracted_text IS NULL AND extraction_failure_code IS NOT NULL AND length(trim(extraction_failure_code)) > 0 AND extracted_at IS NOT NULL)",
            name="ck_resume_documents_extraction_fields",
        ),
        sa.CheckConstraint(
            "(source_type = 'file' AND original_filename IS NOT NULL AND length(trim(original_filename)) > 0 AND storage_key IS NOT NULL AND length(trim(storage_key)) > 0) OR (source_type = 'pastedText' AND original_filename IS NULL AND storage_key IS NULL AND media_type = 'text/plain')",
            name="ck_resume_documents_source_fields",
        ),
        sa.CheckConstraint(
            "extraction_status IN ('pending', 'succeeded', 'failed')",
            name="ck_resume_documents_extraction_status",
        ),
        sa.CheckConstraint(
            "source_type IN ('file', 'pastedText')",
            name="ck_resume_documents_source_type",
        ),
        sa.CheckConstraint(
            "byte_size > 0", name="ck_resume_documents_byte_size_positive"
        ),
        sa.CheckConstraint(
            "length(sha256) = 64", name="ck_resume_documents_sha256_length"
        ),
        sa.ForeignKeyConstraint(
            ["parsing_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key", name="uq_resume_documents_storage_key"),
        sa.UniqueConstraint("user_id", "id", name="uq_resume_documents_user_id_id"),
    )
    op.create_index(
        "ix_resume_documents_extraction_status",
        "resume_documents",
        ["extraction_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_documents_parsing_run_id"),
        "resume_documents",
        ["parsing_run_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_resume_documents_user_id"),
        "resume_documents",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_resume_documents_user_uploaded_at",
        "resume_documents",
        ["user_id", "uploaded_at"],
        unique=False,
    )
    op.create_table(
        "target_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("recruitment_type", sa.String(length=32), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("min_experience_years", sa.Integer(), nullable=True),
        sa.Column("max_experience_years", sa.Integer(), nullable=True),
        sa.Column("preparation_status", sa.String(length=32), nullable=False),
        sa.Column("job_description_status", sa.String(length=32), nullable=False),
        sa.Column("raw_job_description", sa.Text(), nullable=True),
        sa.Column("job_description_version", sa.Integer(), nullable=True),
        sa.Column("job_description_parsing_run_id", sa.Uuid(), nullable=True),
        sa.Column("matching_analysis_run_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(job_description_status = 'missing' AND raw_job_description IS NULL AND job_description_version IS NULL) OR (job_description_status = 'saved' AND raw_job_description IS NOT NULL AND length(trim(raw_job_description)) > 0 AND job_description_version >= 1)"
        ),
        sa.CheckConstraint("job_description_status IN ('missing', 'saved')"),
        sa.CheckConstraint("preparation_status IN ('preparing', 'paused', 'archived')"),
        sa.CheckConstraint("recruitment_type IN ('campus', 'experienced')"),
        sa.CheckConstraint(
            "job_description_version IS NULL OR job_description_version >= 1"
        ),
        sa.CheckConstraint("max_experience_years IS NULL OR max_experience_years >= 0"),
        sa.CheckConstraint(
            "min_experience_years IS NULL OR max_experience_years IS NULL OR max_experience_years >= min_experience_years"
        ),
        sa.CheckConstraint("min_experience_years IS NULL OR min_experience_years >= 0"),
        sa.CheckConstraint("version >= 1"),
        sa.ForeignKeyConstraint(
            ["job_description_parsing_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["matching_analysis_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "id"),
    )
    op.create_index(
        op.f("ix_target_roles_job_description_parsing_run_id"),
        "target_roles",
        ["job_description_parsing_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_target_roles_matching_analysis_run_id"),
        "target_roles",
        ["matching_analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_target_roles_user_id"), "target_roles", ["user_id"], unique=False
    )
    op.create_table(
        "career_profile_project_skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("career_profile_id", sa.Uuid(), nullable=False),
        sa.Column("project_experience_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0"),
        sa.ForeignKeyConstraint(
            ["career_profile_id"], ["career_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_experience_id"],
            ["career_profile_project_experiences.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["career_profile_skills.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_experience_id", "position", deferrable=True, initially="DEFERRED"
        ),
        sa.UniqueConstraint("project_experience_id", "skill_id"),
    )
    op.create_index(
        op.f("ix_career_profile_project_skills_career_profile_id"),
        "career_profile_project_skills",
        ["career_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_profile_project_skills_project_experience_id"),
        "career_profile_project_skills",
        ["project_experience_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_profile_project_skills_skill_id"),
        "career_profile_project_skills",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "career_profile_work_skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("career_profile_id", sa.Uuid(), nullable=False),
        sa.Column("work_experience_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0"),
        sa.ForeignKeyConstraint(
            ["career_profile_id"], ["career_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["career_profile_skills.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_experience_id"],
            ["career_profile_work_experiences.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "work_experience_id", "position", deferrable=True, initially="DEFERRED"
        ),
        sa.UniqueConstraint("work_experience_id", "skill_id"),
    )
    op.create_index(
        op.f("ix_career_profile_work_skills_career_profile_id"),
        "career_profile_work_skills",
        ["career_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_profile_work_skills_skill_id"),
        "career_profile_work_skills",
        ["skill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_profile_work_skills_work_experience_id"),
        "career_profile_work_skills",
        ["work_experience_id"],
        unique=False,
    )
    op.create_table(
        "current_target_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id", "role_id"],
            ["target_roles.user_id", "target_roles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "job_description_analyses",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("job_description_version", sa.Integer(), nullable=False),
        sa.Column("analysis_version", sa.Integer(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("riva_summary", sa.Text(), nullable=False),
        sa.Column("responsibilities", sa.JSON(none_as_null=True), nullable=False),
        sa.Column(
            "qualification_requirements", sa.JSON(none_as_null=True), nullable=False
        ),
        sa.Column("required_skills", sa.JSON(none_as_null=True), nullable=False),
        sa.Column(
            "preferred_qualifications", sa.JSON(none_as_null=True), nullable=False
        ),
        sa.Column("soft_skills", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("business_domains", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "analysis_version >= 1", name="ck_job_description_analyses_analysis_version"
        ),
        sa.CheckConstraint(
            "job_description_version >= 1",
            name="ck_job_description_analyses_jd_version",
        ),
        sa.CheckConstraint(
            "length(trim(riva_summary)) > 0",
            name="ck_job_description_analyses_summary_not_blank",
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "role_id"],
            ["target_roles.user_id", "target_roles.id"],
            name="fk_job_description_analyses_role_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_job_description_analyses_source_run"
        ),
    )
    op.create_index(
        "ix_job_description_analyses_user_role",
        "job_description_analyses",
        ["user_id", "role_id"],
        unique=False,
    )
    op.create_table(
        "matching_analyses",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("job_description_version", sa.Integer(), nullable=False),
        sa.Column("job_description_analysis_version", sa.Integer(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("overall_match_score", sa.Integer(), nullable=False),
        sa.Column("core_requirements_summary", sa.Text(), nullable=False),
        sa.Column("matched_capabilities", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("missing_capabilities", sa.JSON(none_as_null=True), nullable=False),
        sa.Column(
            "underrepresented_capabilities", sa.JSON(none_as_null=True), nullable=False
        ),
        sa.Column("resume_highlights", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("resume_gaps", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("high_risk_questions", sa.JSON(none_as_null=True), nullable=False),
        sa.Column(
            "preparation_recommendations", sa.JSON(none_as_null=True), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "job_description_analysis_version >= 1",
            name="ck_matching_analyses_analysis_version",
        ),
        sa.CheckConstraint(
            "job_description_version >= 1", name="ck_matching_analyses_jd_version"
        ),
        sa.CheckConstraint(
            "length(trim(core_requirements_summary)) > 0",
            name="ck_matching_analyses_summary_not_blank",
        ),
        sa.CheckConstraint(
            "overall_match_score >= 0 AND overall_match_score <= 100",
            name="ck_matching_analyses_score",
        ),
        sa.CheckConstraint(
            "profile_version >= 1", name="ck_matching_analyses_profile_version"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "profile_id"],
            ["career_profiles.user_id", "career_profiles.id"],
            name="fk_matching_analyses_profile_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "role_id"],
            ["target_roles.user_id", "target_roles.id"],
            name="fk_matching_analyses_role_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_matching_analyses_source_run"
        ),
    )
    op.create_index(
        "ix_matching_analyses_user_profile",
        "matching_analyses",
        ["user_id", "profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_matching_analyses_user_role",
        "matching_analyses",
        ["user_id", "role_id"],
        unique=False,
    )
    op.create_table(
        "practice_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("target_role_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("initial_question_type", sa.String(length=64), nullable=False),
        sa.Column("initial_difficulty", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("prioritize_weaknesses", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completion_reason", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'active' AND completed_at IS NULL AND completion_reason IS NULL) OR (status = 'completed' AND completed_at IS NOT NULL AND completion_reason IS NOT NULL)",
            name="ck_practice_sessions_completion_state",
        ),
        sa.CheckConstraint(
            "completion_reason IS NULL OR completion_reason IN ('reviewCompleted', 'userEndedEarly')",
            name="ck_practice_sessions_completion_reason",
        ),
        sa.CheckConstraint(
            "initial_difficulty IN ('basic', 'pressure')",
            name="ck_practice_sessions_initial_difficulty",
        ),
        sa.CheckConstraint(
            "initial_question_type IN ('projectDeepDive', 'behavioral', 'businessUnderstanding', 'motivation', 'technicalFoundation')",
            name="ck_practice_sessions_initial_question_type",
        ),
        sa.CheckConstraint(
            "language IN ('zh-CN', 'en')", name="ck_practice_sessions_language"
        ),
        sa.CheckConstraint(
            "source IN ('personalized', 'saved', 'history')",
            name="ck_practice_sessions_source",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed')", name="ck_practice_sessions_status"
        ),
        sa.CheckConstraint("version >= 1", name="ck_practice_sessions_version"),
        sa.ForeignKeyConstraint(
            ["user_id", "target_role_id"],
            ["target_roles.user_id", "target_roles.id"],
            name="fk_practice_sessions_target_role_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "id", name="uq_practice_sessions_user_id_id"),
    )
    op.create_index(
        op.f("ix_practice_sessions_user_id"),
        "practice_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "question_cards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("target_role_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("matching_analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("question_type", sa.String(length=64), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("assessed_capabilities", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("recommended_materials", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("answer_hints", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("answer_framework", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("follow_up_directions", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("scoring_focus", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("job_description_version", sa.Integer(), nullable=False),
        sa.Column("job_description_analysis_version", sa.Integer(), nullable=False),
        sa.Column("is_saved", sa.Boolean(), nullable=False),
        sa.Column("is_marked_weak", sa.Boolean(), nullable=False),
        sa.Column("answer_hints_revealed", sa.Boolean(), nullable=False),
        sa.Column("answer_framework_revealed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "difficulty IN ('basic', 'pressure')", name="ck_question_cards_difficulty"
        ),
        sa.CheckConstraint(
            "language IN ('zh-CN', 'en')", name="ck_question_cards_language"
        ),
        sa.CheckConstraint(
            "question_type IN ('projectDeepDive', 'behavioral', 'businessUnderstanding', 'motivation', 'technicalFoundation')",
            name="ck_question_cards_question_type",
        ),
        sa.CheckConstraint(
            "job_description_analysis_version >= 1",
            name="ck_question_cards_analysis_version",
        ),
        sa.CheckConstraint(
            "job_description_version >= 1", name="ck_question_cards_jd_version"
        ),
        sa.CheckConstraint(
            "length(trim(prompt)) > 0", name="ck_question_cards_prompt_not_blank"
        ),
        sa.CheckConstraint(
            "profile_version >= 1", name="ck_question_cards_profile_version"
        ),
        sa.ForeignKeyConstraint(
            ["matching_analysis_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "profile_id"],
            ["career_profiles.user_id", "career_profiles.id"],
            name="fk_question_cards_profile_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "target_role_id"],
            ["target_roles.user_id", "target_roles.id"],
            name="fk_question_cards_target_role_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_agent_run_id", name="uq_question_cards_source_run"),
    )
    op.create_index(
        op.f("ix_question_cards_matching_analysis_run_id"),
        "question_cards",
        ["matching_analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_cards_user_id"), "question_cards", ["user_id"], unique=False
    )
    op.create_index(
        "ix_question_cards_user_profile",
        "question_cards",
        ["user_id", "profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_question_cards_user_target_role",
        "question_cards",
        ["user_id", "target_role_id"],
        unique=False,
    )
    op.create_table(
        "resume_parsing_results",
        sa.Column("resume_document_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("result_version", sa.Integer(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("education", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("work_experiences", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("project_experiences", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("skills", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("unresolved_items", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "result_version >= 1", name="ck_resume_parsing_results_result_version"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "resume_document_id"],
            ["resume_documents.user_id", "resume_documents.id"],
            name="fk_resume_parsing_results_document_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("resume_document_id"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_resume_parsing_results_source_run"
        ),
    )
    op.create_index(
        "ix_resume_parsing_results_parsed_at",
        "resume_parsing_results",
        ["parsed_at"],
        unique=False,
    )
    op.create_index(
        "ix_resume_parsing_results_user_document",
        "resume_parsing_results",
        ["user_id", "resume_document_id"],
        unique=False,
    )
    op.create_table(
        "practice_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=64), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("question_generation_run_id", sa.Uuid(), nullable=True),
        sa.Column("question_card_id", sa.Uuid(), nullable=True),
        sa.Column("retry_of_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "difficulty IN ('basic', 'pressure')",
            name="ck_practice_attempts_difficulty",
        ),
        sa.CheckConstraint(
            "question_type IN ('projectDeepDive', 'behavioral', 'businessUnderstanding', 'motivation', 'technicalFoundation')",
            name="ck_practice_attempts_question_type",
        ),
        sa.CheckConstraint(
            "status IN ('generatingQuestion', 'answering', 'answeringFollowUp', 'evaluating', 'review', 'completed', 'endedEarly')",
            name="ck_practice_attempts_status",
        ),
        sa.CheckConstraint(
            "attempt_number >= 1", name="ck_practice_attempts_attempt_number"
        ),
        sa.ForeignKeyConstraint(
            ["question_card_id"], ["question_cards.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["question_generation_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_attempt_id"], ["practice_attempts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "session_id"],
            ["practice_sessions.user_id", "practice_sessions.id"],
            name="fk_practice_attempts_session_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "question_generation_run_id",
            name="uq_practice_attempts_question_generation_run",
        ),
        sa.UniqueConstraint(
            "session_id",
            "attempt_number",
            name="uq_practice_attempts_session_attempt_number",
        ),
    )
    op.create_table(
        "practice_question_reference_contexts",
        sa.Column("question_card_id", sa.Uuid(), nullable=False),
        sa.Column("frozen_context", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_card_id"], ["question_cards.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("question_card_id"),
    )
    op.create_table(
        "resume_import_drafts",
        sa.Column("resume_document_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("parsing_result_version", sa.Integer(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("base_profile_id", sa.Uuid(), nullable=True),
        sa.Column("base_profile_version", sa.Integer(), nullable=True),
        sa.Column("draft_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_action", sa.String(length=32), nullable=False),
        sa.Column("education", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("work_experiences", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("project_experiences", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("skills", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("unresolved_items", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("skipped_items", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("protected_items", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("change_summary", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("applied_profile_version", sa.Integer(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status IN ('ready', 'superseded') AND applied_profile_version IS NULL AND applied_at IS NULL) OR (status = 'applied' AND applied_profile_version IS NOT NULL AND applied_profile_version >= 1 AND applied_at IS NOT NULL)",
            name="ck_resume_import_drafts_applied_state",
        ),
        sa.CheckConstraint(
            "status IN ('ready', 'applied', 'superseded')",
            name="ck_resume_import_drafts_status",
        ),
        sa.CheckConstraint(
            "summary_action IN ('set', 'preserve', 'none')",
            name="ck_resume_import_drafts_summary_action",
        ),
        sa.CheckConstraint(
            "(base_profile_id IS NULL AND base_profile_version IS NULL) OR (base_profile_id IS NOT NULL AND base_profile_version IS NOT NULL AND base_profile_version >= 1)",
            name="ck_resume_import_drafts_base_profile_consistency",
        ),
        sa.CheckConstraint(
            "draft_version >= 1", name="ck_resume_import_drafts_draft_version"
        ),
        sa.CheckConstraint(
            "parsing_result_version >= 1",
            name="ck_resume_import_drafts_parsing_result_version",
        ),
        sa.ForeignKeyConstraint(
            ["resume_document_id"],
            ["resume_parsing_results.resume_document_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "resume_document_id"],
            ["resume_documents.user_id", "resume_documents.id"],
            name="fk_resume_import_drafts_document_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("resume_document_id"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_resume_import_drafts_source_run"
        ),
    )
    op.create_index(
        "ix_resume_import_drafts_user_document",
        "resume_import_drafts",
        ["user_id", "resume_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_resume_import_drafts_user_status_updated_at",
        "resume_import_drafts",
        ["user_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "practice_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("dimension_scores", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("focus_assessments", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name="ck_practice_evaluations_overall_score",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["practice_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", name="uq_practice_evaluations_attempt"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_practice_evaluations_source_run"
        ),
    )
    op.create_index(
        op.f("ix_practice_evaluations_attempt_id"),
        "practice_evaluations",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_follow_up_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("focus", sa.Text(), nullable=False),
        sa.Column("answer_hints", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("answer_framework", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("answer_hints_revealed", sa.Boolean(), nullable=False),
        sa.Column("answer_framework_revealed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            '"order" >= 1', name="ck_practice_follow_up_questions_order"
        ),
        sa.CheckConstraint(
            "length(trim(focus)) > 0 AND length(focus) <= 1000",
            name="ck_practice_follow_up_questions_focus",
        ),
        sa.CheckConstraint(
            "length(trim(prompt)) > 0 AND length(prompt) <= 4000",
            name="ck_practice_follow_up_questions_prompt",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["practice_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "order", name="uq_practice_follow_up_questions_attempt_order"
        ),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_practice_follow_up_questions_source_run"
        ),
    )
    op.create_index(
        op.f("ix_practice_follow_up_questions_attempt_id"),
        "practice_follow_up_questions",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("next_question_type", sa.String(length=64), nullable=True),
        sa.Column("next_difficulty", sa.String(length=32), nullable=True),
        sa.Column("focus_areas", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("recommended_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "((action = 'retryCurrent' AND next_question_type IS NULL AND next_difficulty IS NULL) OR (action = 'nextQuestion' AND next_question_type IS NOT NULL AND next_difficulty IS NOT NULL))",
            name="ck_practice_recommendations_action_plan",
        ),
        sa.CheckConstraint(
            "action IN ('retryCurrent', 'nextQuestion')",
            name="ck_practice_recommendations_action",
        ),
        sa.CheckConstraint(
            "next_difficulty IS NULL OR next_difficulty IN ('basic', 'pressure')",
            name="ck_practice_recommendations_difficulty",
        ),
        sa.CheckConstraint(
            "next_question_type IS NULL OR next_question_type IN ('projectDeepDive', 'behavioral', 'businessUnderstanding', 'motivation', 'technicalFoundation')",
            name="ck_practice_recommendations_question_type",
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0 AND length(reason) <= 2000",
            name="ck_practice_recommendations_reason",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["practice_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", name="uq_practice_recommendations_attempt"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_practice_recommendations_source_run"
        ),
    )
    op.create_index(
        op.f("ix_practice_recommendations_attempt_id"),
        "practice_recommendations",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("overall_performance", sa.Text(), nullable=False),
        sa.Column("highlights", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("main_issues", sa.JSON(none_as_null=True), nullable=False),
        sa.Column(
            "improvement_suggestions", sa.JSON(none_as_null=True), nullable=False
        ),
        sa.Column(
            "reusable_answer_structure", sa.JSON(none_as_null=True), nullable=False
        ),
        sa.Column("exposed_weaknesses", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(overall_performance)) > 0 AND length(overall_performance) <= 4000",
            name="ck_practice_reviews_overall_performance",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["practice_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", name="uq_practice_reviews_attempt"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_practice_reviews_source_run"
        ),
    )
    op.create_index(
        op.f("ix_practice_reviews_attempt_id"),
        "practice_reviews",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("follow_up_question_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('"order" >= 1', name="ck_practice_answers_order"),
        sa.CheckConstraint(
            "((kind = 'main' AND \"order\" = 1 AND follow_up_question_id IS NULL) OR (kind = 'followUp' AND \"order\" >= 2 AND follow_up_question_id IS NOT NULL))",
            name="ck_practice_answers_kind_order_question",
        ),
        sa.CheckConstraint(
            "length(trim(content)) > 0 AND length(content) <= 20000",
            name="ck_practice_answers_content",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["practice_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["follow_up_question_id"],
            ["practice_follow_up_questions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "order", name="uq_practice_answers_attempt_order"
        ),
        sa.UniqueConstraint(
            "follow_up_question_id", name="uq_practice_answers_follow_up_question"
        ),
    )
    op.create_index(
        op.f("ix_practice_answers_attempt_id"),
        "practice_answers",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_follow_up_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("follow_up_question_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "((action = 'askFollowUp' AND follow_up_question_id IS NOT NULL) OR (action = 'complete' AND follow_up_question_id IS NULL))",
            name="ck_practice_follow_up_decisions_action_question",
        ),
        sa.CheckConstraint(
            "action IN ('askFollowUp', 'complete')",
            name="ck_practice_follow_up_decisions_action",
        ),
        sa.CheckConstraint(
            '"order" >= 1 AND "order" <= 2',
            name="ck_practice_follow_up_decisions_order",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["practice_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["follow_up_question_id"],
            ["practice_follow_up_questions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "order", name="uq_practice_follow_up_decisions_attempt_order"
        ),
        sa.UniqueConstraint(
            "follow_up_question_id", name="uq_practice_follow_up_decisions_question"
        ),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_practice_follow_up_decisions_source_run"
        ),
    )
    op.create_index(
        op.f("ix_practice_follow_up_decisions_attempt_id"),
        "practice_follow_up_decisions",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_reference_answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_card_id", sa.Uuid(), nullable=False),
        sa.Column("follow_up_question_id", sa.Uuid(), nullable=True),
        sa.Column("source_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("addressed_gap", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("key_points", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("common_mistakes", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "((target_type = 'main' AND follow_up_question_id IS NULL AND kind IN ('personalizedExample', 'technicalReference') AND addressed_gap IS NULL) OR (target_type = 'followUp' AND follow_up_question_id IS NOT NULL AND kind IN ('personalizedSupplement', 'technicalReference') AND addressed_gap IS NOT NULL AND length(trim(addressed_gap)) > 0))",
            name="ck_practice_reference_answers_target_kind",
        ),
        sa.ForeignKeyConstraint(
            ["follow_up_question_id"],
            ["practice_follow_up_questions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_card_id"], ["question_cards.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_agent_run_id", name="uq_practice_reference_answers_source_run"
        ),
    )
    op.create_index(
        op.f("ix_practice_reference_answers_follow_up_question_id"),
        "practice_reference_answers",
        ["follow_up_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_reference_answers_question_card_id"),
        "practice_reference_answers",
        ["question_card_id"],
        unique=False,
    )
    op.create_index(
        "uq_practice_reference_answers_follow_up_target",
        "practice_reference_answers",
        ["follow_up_question_id"],
        unique=True,
        postgresql_where=sa.text("target_type = 'followUp'"),
        sqlite_where=sa.text("target_type = 'followUp'"),
    )
    op.create_index(
        "uq_practice_reference_answers_main_target",
        "practice_reference_answers",
        ["question_card_id"],
        unique=True,
        postgresql_where=sa.text("target_type = 'main'"),
        sqlite_where=sa.text("target_type = 'main'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_practice_reference_answers_main_target",
        table_name="practice_reference_answers",
        postgresql_where=sa.text("target_type = 'main'"),
        sqlite_where=sa.text("target_type = 'main'"),
    )
    op.drop_index(
        "uq_practice_reference_answers_follow_up_target",
        table_name="practice_reference_answers",
        postgresql_where=sa.text("target_type = 'followUp'"),
        sqlite_where=sa.text("target_type = 'followUp'"),
    )
    op.drop_index(
        op.f("ix_practice_reference_answers_question_card_id"),
        table_name="practice_reference_answers",
    )
    op.drop_index(
        op.f("ix_practice_reference_answers_follow_up_question_id"),
        table_name="practice_reference_answers",
    )
    op.drop_table("practice_reference_answers")
    op.drop_index(
        op.f("ix_practice_follow_up_decisions_attempt_id"),
        table_name="practice_follow_up_decisions",
    )
    op.drop_table("practice_follow_up_decisions")
    op.drop_index(op.f("ix_practice_answers_attempt_id"), table_name="practice_answers")
    op.drop_table("practice_answers")
    op.drop_index(op.f("ix_practice_reviews_attempt_id"), table_name="practice_reviews")
    op.drop_table("practice_reviews")
    op.drop_index(
        op.f("ix_practice_recommendations_attempt_id"),
        table_name="practice_recommendations",
    )
    op.drop_table("practice_recommendations")
    op.drop_index(
        op.f("ix_practice_follow_up_questions_attempt_id"),
        table_name="practice_follow_up_questions",
    )
    op.drop_table("practice_follow_up_questions")
    op.drop_index(
        op.f("ix_practice_evaluations_attempt_id"), table_name="practice_evaluations"
    )
    op.drop_table("practice_evaluations")
    op.drop_index(
        "ix_resume_import_drafts_user_status_updated_at",
        table_name="resume_import_drafts",
    )
    op.drop_index(
        "ix_resume_import_drafts_user_document", table_name="resume_import_drafts"
    )
    op.drop_table("resume_import_drafts")
    op.drop_table("practice_question_reference_contexts")
    op.drop_table("practice_attempts")
    op.drop_index(
        "ix_resume_parsing_results_user_document", table_name="resume_parsing_results"
    )
    op.drop_index(
        "ix_resume_parsing_results_parsed_at", table_name="resume_parsing_results"
    )
    op.drop_table("resume_parsing_results")
    op.drop_index("ix_question_cards_user_target_role", table_name="question_cards")
    op.drop_index("ix_question_cards_user_profile", table_name="question_cards")
    op.drop_index(op.f("ix_question_cards_user_id"), table_name="question_cards")
    op.drop_index(
        op.f("ix_question_cards_matching_analysis_run_id"), table_name="question_cards"
    )
    op.drop_table("question_cards")
    op.drop_index(op.f("ix_practice_sessions_user_id"), table_name="practice_sessions")
    op.drop_table("practice_sessions")
    op.drop_index("ix_matching_analyses_user_role", table_name="matching_analyses")
    op.drop_index("ix_matching_analyses_user_profile", table_name="matching_analyses")
    op.drop_table("matching_analyses")
    op.drop_index(
        "ix_job_description_analyses_user_role", table_name="job_description_analyses"
    )
    op.drop_table("job_description_analyses")
    op.drop_table("current_target_roles")
    op.drop_index(
        op.f("ix_career_profile_work_skills_work_experience_id"),
        table_name="career_profile_work_skills",
    )
    op.drop_index(
        op.f("ix_career_profile_work_skills_skill_id"),
        table_name="career_profile_work_skills",
    )
    op.drop_index(
        op.f("ix_career_profile_work_skills_career_profile_id"),
        table_name="career_profile_work_skills",
    )
    op.drop_table("career_profile_work_skills")
    op.drop_index(
        op.f("ix_career_profile_project_skills_skill_id"),
        table_name="career_profile_project_skills",
    )
    op.drop_index(
        op.f("ix_career_profile_project_skills_project_experience_id"),
        table_name="career_profile_project_skills",
    )
    op.drop_index(
        op.f("ix_career_profile_project_skills_career_profile_id"),
        table_name="career_profile_project_skills",
    )
    op.drop_table("career_profile_project_skills")
    op.drop_index(op.f("ix_target_roles_user_id"), table_name="target_roles")
    op.drop_index(
        op.f("ix_target_roles_matching_analysis_run_id"), table_name="target_roles"
    )
    op.drop_index(
        op.f("ix_target_roles_job_description_parsing_run_id"),
        table_name="target_roles",
    )
    op.drop_table("target_roles")
    op.drop_index("ix_resume_documents_user_uploaded_at", table_name="resume_documents")
    op.drop_index(op.f("ix_resume_documents_user_id"), table_name="resume_documents")
    op.drop_index(
        op.f("ix_resume_documents_parsing_run_id"), table_name="resume_documents"
    )
    op.drop_index(
        "ix_resume_documents_extraction_status", table_name="resume_documents"
    )
    op.drop_table("resume_documents")
    op.drop_index(
        op.f("ix_career_profile_work_experiences_career_profile_id"),
        table_name="career_profile_work_experiences",
    )
    op.drop_table("career_profile_work_experiences")
    op.drop_index(
        op.f("ix_career_profile_skills_career_profile_id"),
        table_name="career_profile_skills",
    )
    op.drop_table("career_profile_skills")
    op.drop_index(
        op.f("ix_career_profile_project_experiences_career_profile_id"),
        table_name="career_profile_project_experiences",
    )
    op.drop_table("career_profile_project_experiences")
    op.drop_index(
        op.f("ix_career_profile_educations_career_profile_id"),
        table_name="career_profile_educations",
    )
    op.drop_table("career_profile_educations")
    op.drop_index(op.f("ix_career_profiles_user_id"), table_name="career_profiles")
    op.drop_table("career_profiles")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_digest"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_agent_runs_user_created", table_name="agent_runs")
    op.drop_index(
        "ix_agent_runs_queued_available",
        table_name="agent_runs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_index(
        "ix_agent_runs_expired_running",
        table_name="agent_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_users_normalized_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
